name: eat_smart
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  api_repository:
    path: packages/api_repository
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.1
  cloud_firestore: ^4.5.1
  easy_container: ^1.0.4+1
  equatable: ^2.0.5
  firebase_core: ^2.9.0
  firebase_phone_auth_handler: ^1.0.8
  firebase_storage: ^11.1.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutterfire_ui: ^0.4.3+20
  form_builder_validators: ^8.5.0
  go_router: ^6.5.6
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+3
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  pinput: ^2.2.31
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
